from src.agents.insight_agent import InsightAgent


agent = InsightAgent()


request = {
    "intent": "distribution",
    "metric_name": "humidity",
    "room": None,
    "room_names": [],
    "distribution_top_n": 4,
    "top_n": 4,
    "ascending": False,
}


rows = [
    {
        "value": 58.0,
        "display_name": "Dining Room",
        "ranking_value": 54.62,
        "room_rank": 1,
        "selection_type": "top",
    },
    {
        "value": 56.0,
        "display_name": "Dining Room",
        "ranking_value": 54.62,
        "room_rank": 1,
        "selection_type": "top",
    },
    {
        "value": 52.0,
        "display_name": "Specialist Room 22",
        "ranking_value": 53.10,
        "room_rank": 2,
        "selection_type": "top",
    },
    {
        "value": 50.0,
        "display_name": "Seminar Room 2",
        "ranking_value": 52.40,
        "room_rank": 3,
        "selection_type": "top",
    },
    {
        "value": 49.0,
        "display_name": "Office Room 11A",
        "ranking_value": 51.80,
        "room_rank": 4,
        "selection_type": "top",
    },
]


result = agent.generate(
    user_query=
        "Show the humidity distribution of top 4 rooms",

    request=
        request,

    query_type=
        "distribution",

    rows=
        rows,

    row_count=
        len(rows),

    result_valid=
        True,

    result_has_data=
        True,

    result_warnings=
        [],

    truncated=
        False,
)


print("\n" + "=" * 80)

print("INSIGHT RESULT")

print("=" * 80)

print(
    "\nGenerated by:",
    result["generated_by"]
)

print(
    "\nSummary:"
)

print(
    result["summary"]
)

print(
    "\nKey points:"
)

for point in result["key_points"]:

    print(
        "-",
        point
    )

print(
    "\nCaution:"
)

print(
    result["caution"]
)

print(
    "\nDeterministic facts:"
)

print(
    result["facts"]
)

print(
    "\nError:"
)

print(
    result["error"]
)