from src.multi_agent_graph import SmartVizMultiAgentGraph


def print_result(state: dict) -> None:

    print("\n" + "=" * 80)
    print("FINAL RESULT")
    print("=" * 80)

    # ========================================================
    # INTENT
    # ========================================================

    print("\nIntent:")
    print(
        state.get(
            "intent"
        )
    )

    # ========================================================
    # MAPPING
    # ========================================================

    print("\nMapping:")
    print(
        state.get(
            "mapping"
        )
    )

    # ========================================================
    # REQUEST VALIDATION
    # ========================================================

    print("\nValidation:")
    print(
        state.get(
            "validation"
        )
    )

    # ========================================================
    # QUERY
    # ========================================================

    print("\nQuery type:")
    print(
        state.get(
            "query_type"
        )
    )

    # ========================================================
    # SQL EXECUTION
    # ========================================================

    print("\nExecution successful:")
    print(
        state.get(
            "execution_success"
        )
    )

    print("\nRows returned:")
    print(
        state.get(
            "sql_row_count"
        )
    )

    print("\nRows stored:")
    print(
        state.get(
            "sql_stored_row_count"
        )
    )

    print("\nResult truncated:")
    print(
        state.get(
            "sql_result_truncated"
        )
    )

    # ========================================================
    # RESULT VALIDATION
    # ========================================================

    print("\nResult validation:")
    print(
        state.get(
            "result_validation"
        )
    )

    print("\nResult status:")
    print(
        state.get(
            "result_status"
        )
    )

    # ========================================================
    # VISUALIZATION
    # ========================================================

    print("\n" + "-" * 80)
    print("VISUALIZATION")
    print("-" * 80)

    print("\nVisualization:")
    print(
        state.get(
            "visualization"
        )
    )

    print("\nVisualization successful:")
    print(
        state.get(
            "visualization_success"
        )
    )

    print("\nChart created:")
    print(
        state.get(
            "chart_created"
        )
    )

    print("\nChart type:")
    print(
        state.get(
            "final_chart_type"
        )
    )

    print("\nChart title:")
    print(
        state.get(
            "chart_title"
        )
    )

    print("\nChart path:")
    print(
        state.get(
            "chart_path"
        )
    )

    # ========================================================
    # FINAL INSIGHT
    # ========================================================

    print("\n" + "=" * 80)
    print("FINAL INSIGHT")
    print("=" * 80)

    print(
        "\nInsight generation success:"
    )

    print(
        state.get(
            "insight_generation_success"
        )
    )

    print(
        "\nInsight guard valid:"
    )

    print(
        state.get(
            "insight_guard_valid"
        )
    )

    print(
        "\nInsight fallback used:"
    )

    print(
        state.get(
            "insight_used_fallback"
        )
    )

    print(
        "\nGenerated by:"
    )

    print(
        state.get(
            "insight_generated_by"
        )
    )

    print(
        "\nSummary:"
    )

    print(
        state.get(
            "insight_summary",
            "",
        )
    )

    print(
        "\nKey points:"
    )

    key_points = (
        state.get(
            "insight_key_points",
            [],
        )
        or []
    )

    if key_points:

        for point in key_points:

            print(
                "-",
                point,
            )

    else:

        print(
            "No key points generated."
        )

    print(
        "\nCaution:"
    )

    caution = (
        state.get(
            "insight_caution",
            "",
        )
        or ""
    )

    if caution:

        print(
            caution
        )

    else:

        print(
            "None"
        )

    # ========================================================
    # INSIGHT GUARD DETAILS
    # ========================================================

    insight_guard = (
        state.get(
            "insight_guard",
            {},
        )
        or {}
    )

    guard_reasons = (
        insight_guard.get(
            "reasons",
            [],
        )
        if isinstance(
            insight_guard,
            dict,
        )
        else []
    )

    if guard_reasons:

        print(
            "\nInsight Guard reasons:"
        )

        for reason in guard_reasons:

            print(
                "-",
                reason,
            )

    # ========================================================
    # WARNINGS
    # ========================================================

    warnings = (
        state.get(
            "warnings",
            [],
        )
        or []
    )

    if warnings:

        print(
            "\nWarnings:"
        )

        for warning in warnings:

            print(
                "-",
                warning,
            )

    # ========================================================
    # SQL SAMPLE
    # ========================================================

    rows = (
        state.get(
            "sql_results",
            [],
        )
        or []
    )

    print("\n" + "-" * 80)
    print("SQL RESULT SAMPLE")
    print("-" * 80)

    if rows:

        print(
            f"\nShowing first "
            f"{min(20, len(rows))} "
            f"stored row(s):\n"
        )

        for row in rows[:20]:

            print(
                row
            )

    else:

        print(
            "\nNo results returned."
        )

    # ========================================================
    # ERRORS
    # ========================================================

    errors = (
        state.get(
            "errors",
            [],
        )
        or []
    )

    if errors:

        print(
            "\nErrors:"
        )

        for error in errors:

            print(
                "-",
                error,
            )

    # ========================================================
    # END
    # ========================================================

    print("\n" + "=" * 80)


def main() -> None:

    print("=" * 80)
    print("SMARTVIZ MULTI-AGENT SQL ASSISTANT")
    print("=" * 80)

    print(
        "\nType a SmartViz question."
    )

    print(
        "Type 'exit' to stop.\n"
    )

    # ========================================================
    # BUILD GRAPH ONCE
    # ========================================================

    graph = (
        SmartVizMultiAgentGraph()
    )

    # ========================================================
    # INTERACTIVE LOOP
    # ========================================================

    while True:

        user_query = input(
            "\nAsk SmartViz > "
        ).strip()

        if not user_query:

            print(
                "Please enter a question."
            )

            continue

        if user_query.casefold() in {
            "exit",
            "quit",
            "q",
        }:

            print(
                "\nSmartViz assistant stopped."
            )

            break

        print(
            "\n"
            + "=" * 80
        )

        print(
            f"USER QUERY: "
            f"{user_query}"
        )

        print(
            "=" * 80
        )

        try:

            # ------------------------------------------------
            # Use the public run() method.
            #
            # This initialises the LangGraph state correctly
            # and invokes the compiled graph.
            # ------------------------------------------------

            result = (
                graph.run(
                    user_query
                )
            )

            print_result(
                result
            )

        except Exception as error:

            print(
                "\n❌ Pipeline failed:"
            )

            print(
                f"{type(error).__name__}: "
                f"{error}"
            )


if __name__ == "__main__":

    main()