from src.baseline.hybrid_single_agent import HybridSingleAgent


def main() -> None:

    print("=" * 80)
    print("HYBRID SINGLE-AGENT BASELINE")
    print("=" * 80)

    system = HybridSingleAgent()

    while True:

        query = input(
            "\nAsk baseline > "
        ).strip()

        if query.casefold() in {
            "exit",
            "quit",
            "q",
        }:

            break

        if not query:

            continue

        try:

            result = system.run(
                query
            )

            print("\n" + "=" * 80)
            print("RESULT")
            print("=" * 80)

            print(
                "\nParser source:",
                result.get(
                    "parser_source"
                ),
            )

            print(
                "\nIntent:",
                result.get(
                    "intent"
                ),
            )

            print(
                "\nMapping:"
            )

            print(
                result.get(
                    "mapping"
                )
            )

            print(
                "\nQuery type:",
                result.get(
                    "query_type"
                ),
            )

            print(
                "\nExecution successful:",
                result.get(
                    "execution_success"
                ),
            )

            print(
                "\nRows:",
                result.get(
                    "sql_row_count"
                ),
            )

            print(
                "\nResult status:",
                result.get(
                    "result_status"
                ),
            )

            print(
                "\nSelected chart:",
                result.get(
                    "chart_type"
                ),
            )

            print(
                "\nGenerated chart:",
                result.get(
                    "final_chart_type"
                ),
            )

            print(
                "\nChart created:",
                result.get(
                    "chart_created"
                ),
            )

            print(
                "\nChart path:"
            )

            print(
                result.get(
                    "chart_path"
                )
            )

            print("\n" + "-" * 80)
            print("SINGLE-AGENT INSIGHT")
            print("-" * 80)

            print(
                "\nGenerated by:",
                result.get(
                    "insight_generated_by"
                ),
            )

            print(
                "\nSummary:"
            )

            print(
                result.get(
                    "insight_summary"
                )
            )

            print(
                "\nKey points:"
            )

            for point in (
                result.get(
                    "insight_key_points",
                    [],
                )
                or []
            ):

                print(
                    "-",
                    point,
                )

            print(
                "\nCaution:"
            )

            print(
                result.get(
                    "insight_caution"
                )
                or
                "None"
            )

            warnings = (
                result.get(
                    "warnings",
                    [],
                )
                or []
            )

            if warnings:

                print(
                    "\nWarnings:"
                )

                for warning in warnings:

                    print(
                        "-",
                        warning,
                    )

            errors = (
                result.get(
                    "errors",
                    [],
                )
                or []
            )

            if errors:

                print(
                    "\nErrors:"
                )

                for error in errors:

                    print(
                        "-",
                        error,
                    )

        except Exception as error:

            print(
                "\n❌ Baseline failed:"
            )

            print(
                f"{type(error).__name__}: "
                f"{error}"
            )


if __name__ == "__main__":

    main()