from src.agents.insight_agent import InsightAgent
from src.agents.insight_guard import InsightGuard


agent = InsightAgent()

guard = InsightGuard()


request = {
    "intent": "distribution",
    "metric_name": "humidity",
    "room": None,
    "room_names": [],
    "distribution_top_n": 4,
    "top_n": 4,
    "ascending": False,
}


rows = [
    {
        "value": 58.0,
        "display_name": "Dining Room",
        "ranking_value": 54.62,
        "room_rank": 1,
        "selection_type": "top",
    },
    {
        "value": 56.0,
        "display_name": "Dining Room",
        "ranking_value": 54.62,
        "room_rank": 1,
        "selection_type": "top",
    },
    {
        "value": 52.0,
        "display_name": "Specialist Room 22",
        "ranking_value": 53.10,
        "room_rank": 2,
        "selection_type": "top",
    },
    {
        "value": 50.0,
        "display_name": "Seminar Room 2",
        "ranking_value": 52.40,
        "room_rank": 3,
        "selection_type": "top",
    },
    {
        "value": 49.0,
        "display_name": "Office Room 11A",
        "ranking_value": 51.80,
        "room_rank": 4,
        "selection_type": "top",
    },
]


raw_insight = agent.generate(
    user_query=
        "Show the humidity distribution of top 4 rooms",

    request=
        request,

    query_type=
        "distribution",

    rows=
        rows,

    row_count=
        len(rows),

    result_valid=
        True,

    result_has_data=
        True,

    result_warnings=
        [],

    truncated=
        False,
)


guarded_result = guard.guard(
    raw_insight
)


final_insight = (
    guarded_result[
        "insight"
    ]
)


print(
    "\n"
    + "=" * 80
)

print(
    "RAW INSIGHT"
)

print(
    "=" * 80
)

print(
    "\nGenerated by:",
    raw_insight[
        "generated_by"
    ],
)

print(
    "\nSummary:"
)

print(
    raw_insight[
        "summary"
    ]
)

print(
    "\nKey points:"
)

for point in raw_insight[
    "key_points"
]:

    print(
        "-",
        point,
    )


print(
    "\n"
    + "=" * 80
)

print(
    "INSIGHT GUARD"
)

print(
    "=" * 80
)

print(
    "\nUsed fallback:",
    guarded_result[
        "used_fallback"
    ],
)

print(
    "\nGuard reasons:"
)

for reason in guarded_result[
    "reasons"
]:

    print(
        "-",
        reason,
    )


print(
    "\n"
    + "=" * 80
)

print(
    "FINAL GUARDED INSIGHT"
)

print(
    "=" * 80
)

print(
    "\nGenerated by:",
    final_insight[
        "generated_by"
    ],
)

print(
    "\nSummary:"
)

print(
    final_insight[
        "summary"
    ]
)

print(
    "\nKey points:"
)

for point in final_insight[
    "key_points"
]:

    print(
        "-",
        point,
    )

print(
    "\nCaution:"
)

print(
    final_insight[
        "caution"
    ]
)

print(
    "\nGuard status:",
    final_insight[
        "guard_status"
    ],
)

print(
    "\nError:",
    final_insight[
        "error"
    ],
)